"""empty message

Revision ID: 3e3ffcf756f4
Revises: 6c476e731f0c
Create Date: 2020-02-10 22:36:19.986512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3ffcf756f4'
down_revision = '6c476e731f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Artist_name'), 'Artist', ['name'], unique=False)
    op.create_index(op.f('ix_Venue_name'), 'Venue', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Venue_name'), table_name='Venue')
    op.drop_index(op.f('ix_Artist_name'), table_name='Artist')
    # ### end Alembic commands ###
